import numpy as np


class Map:
    """
    Class to keep track of the map, keeping track of nodes, pheromones and ants
    """

    def __init__(self, nodes: list, ants: list):
        """
        nodes: list of tuples holding coordinates for the location of nodes
        """
        self.nodes = nodes

        # Matrix to store the distance between nodes
        # Eg: if distance_matrx[1, 2] = 12, the distance between node 1 and node 2 is 12
        # This matrix is currently symmetric, but doesn't need to be
        self.distance_matrix = np.zeros((len(nodes), len(nodes)))
        self._compute_distance_matrix()

        # Matrix to store pheromone levels between nodes
        # The indexing is the same as above, for example:
        # pheromone_matrix[1, 2] = 0.7 means the amount of pheromone deposited between node 1 and 2 is 0.7
        self.pheromone_matrix = np.full((len(nodes), len(nodes)), 0.01)

        # Controls how quickly pheromone trails evaporate
        self.pheromone_evaporation_coefficient = 0.6

        # Matrix to store desirability of transition from node x to node y
        # desirability_matrix[1, 2] = 0.4 means the desirability to go from node 1 to node 2 is 0.4
        self.desirability_matrix = 1 / self.distance_matrix

        # List of ant objects
        self.ants = ants

    def calculate_distance(self, beginning, end):
        """
        Compute the euclidean distance between two nodes
        """
        beg_vec = np.array(beginning)
        end_vec = np.array(end)

        return np.linalg.norm(beg_vec - end_vec)

    def _compute_distance_matrix(self):
        """
        Generate the distance matrix using the euclidean norm
        """
        for node1_idx in range(len(self.nodes)):
            for node2_idx in range(len(self.nodes)):
                distance = self.calculate_distance(
                    self.nodes[node1_idx], self.nodes[node2_idx])
                if distance == 0:
                    distance = 0.01
                self.distance_matrix[node1_idx, node2_idx] = distance

    def pheromone_decay(self):
        """
        Decays existing pheromone trails
        To be performed before the ants update trails
        """
        self.pheromone_matrix *= self.pheromone_evaporation_coefficient

    def pheromone_update(self):
        """
        Decays and updates pheromones trails
        """
        self.pheromone_decay()
        # Create new pheromones
        for ant in self.ants:
            ant.deposit_pheromones(self)

    def distribute_ants(self):
        """
        Uniformly distribute the ants across all the nodes
        """
        for idx, ant in enumerate(self.ants):
            ant.path.append(idx % len(self.nodes))

    def move_ants(self):
        """
        Move all ants one step forward
        """
        for ant in self.ants:
            ant.move(self)

    def find_paths(self):
        """
        Find a complete path for each ant.
        Ensures this is a closed path.
        Assumes each ant has a starting element in its path,
        generated by calling distribute_ants()
        """
        for i in range(len(self.nodes) - 1):
            self.move_ants()

        # Add the first node at the end to close the path
        for ant in self.ants:
            ant.path.append(ant.path[0])

    def reset_ants(self):
        """
        Reset the position of all ants.
        Their initial position is determined by the uniform distribution
        """
        for ant in self.ants:
            ant.reset_position()

    def normalise_path(self, path):
        """
        Normalise a cyclic path by rotating so it starts at the smallest node.
        Removes the duplicated end value.
        """
        if path[0] == path[-1]:
            path = path[:-1]  # remove duplicate end

        # Find index of minimum node
        min_idx = path.index(min(path))

        # Rotate path so it starts at the smallest node
        rotated = path[min_idx:] + path[:min_idx]

        # Ensure that the reverse path is treated the same as the forward one
        reversed_rotated = list(reversed(path[min_idx:] + path[:min_idx]))

        return min(rotated, reversed_rotated)

    def paths_stagnant(self):
        """
        Compares the paths of each ant after a full cycle.
        If each ant performs the same cycle we have reached
        a stagnant state, so we return True.
        Note that we ignore rotation direction and starting point
        """
        base_path = self.normalise_path(self.ants[0].path)
        for ant in self.ants[1:]:
            if base_path != self.normalise_path(ant.path):
                return False

        return True

    def find_best_path(self):
        """
        Finds the best path found by an ant.
        Returns the path and its associated length
        """
        best_path = None
        best_length = float("inf")
        for ant in self.ants:
            length = ant.calculate_tour_length(self)
            if length < best_length:
                best_length = length
                best_path = ant.path.copy()

        return best_path, best_length

    def step(self):
        """
        Function to be called repeatedly.
        Completes one cycle of all ants finding a path,
        updating the pheromones and resetting them to the start.
        Keeps track of the best path this cycle.
        Returns:
            stagnated (bool): Whether all ants converged to the same tour
            best_path (list): Best path found this cycle
            best_length (float): Length of best path
        """
        # Find possible paths
        self.find_paths()

        # Keep the best path found
        best_path, best_length = self.find_best_path()

        # Update pheromones
        self.pheromone_update()

        # Check for stagnating behaviour
        stagnated = self.paths_stagnant()

        # Reset position of ants if not stagnated
        if not stagnated:
            self.reset_ants()

        return stagnated, best_path, best_length

    def main(self, max_cycles=1000, spread_ants=True, verbose=True):
        if spread_ants:
            self.distribute_ants()

        global_best_path = None
        global_best_length = float("inf")
        for i in range(max_cycles):
            stagnated, cycle_best_path, cycle_best_length = self.step()

            if cycle_best_length < global_best_length:
                global_best_length = cycle_best_length
                global_best_path = cycle_best_path
                if verbose:
                    print(f"New best path of length {
                          global_best_length} found at cycle {i + 1}.")

            if stagnated:
                if verbose:
                    print(f"Stagnation detected at cycle {
                          i + 1}. Terminating.")
                break
        else:
            if verbose:
                print(f"Reached max iteration count ({max_cycles}).")

        print(f"Best found path is {
              global_best_path} with a length of {global_best_length}.")

        return global_best_path, global_best_length
